# Generated by Django 3.0.8 on 2020-09-23 07:40

import aggregator.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='newsModel',
            fields=[
                ('id', models.BigIntegerField(db_column='Aricle-ID', default=aggregator.models.random_num, primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='Title', max_length=200)),
                ('body', models.TextField(db_column='Detail')),
                ('article_url', models.URLField(db_column='Link')),
                ('image', models.URLField(blank=True, null=True)),
                ('date', models.CharField(db_column='Date', default='None', max_length=50)),
            ],
        ),
    ]
